# Generated by Django 5.0.2 on 2024-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar_user_bio_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_user',
            field=models.ImageField(blank=True, upload_to='imges/'),
        ),
    ]
